[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[project]
name = "cuss"
version = "0.1.0"
description = "Code Usage Statistics"
readme = "README.md"
authors = [
  { name = "Joren Hammudoglu", email = "jhammudoglu@gmail.com" },
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
keywords = [
  "api",
  "ast",
  "code-search",
  "deprecation",
  "public-api",
  "static-analysis",
  "type-stubs",
  "usage-statistics",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development",
  "Typing :: Typed",
]
requires-python = ">=3.14"
dependencies = ["httpx>=0.28.1"]

[project.urls]
Homepage = "https://github.com/jorenham/cuss"
Repository = "https://github.com/jorenham/cuss"
Issues = "https://github.com/jorenham/cuss/issues"

[project.scripts]
cuss = "cuss:main"

[dependency-groups]
dev = [
  "basedpyright==1.39.9",
  "dprint-py==0.55.2.0",
  "pyrefly==1.2.0",
  "pytest==9.1.1",
  "ruff==0.16.2",
]

# [based]pyright

[tool.pyright]
pythonPlatform = "All"
include = ["src/cuss"]
ignore = [".venv"]
stubPath = "."
typeCheckingMode = "all"
useLibraryCodeForTypes = false
enableReachabilityAnalysis = true
reportAny = false
reportExplicitAny = false
reportPrivateUsage = false # dupe of PLC2701
reportPrivateImportUsage = false # dupe of PLC2701
reportUnusedImport = false # dupe of F401
reportUnusedVariable = false # dupe of F841

# pytest

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["src/cuss", "tests"]
addopts = ["-ra", "--doctest-modules"]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL", "ELLIPSIS"]
filterwarnings = ["error"]
log_level = "INFO"
strict = true

# ruff

[tool.ruff]
src = ["src/cuss", "tests"]
extend-exclude = [".git", ".venv"]
force-exclude = true
show-fixes = true
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "any-type", # flake8-annotations
  "assert", # flake8-bandit
  "FBT", # flake8-boolean-trap
  "CPY", # flake8-copyright
  "FIX", # flake8-fixme
  "D", # pydocstyle
  "docstring-missing-returns", # pydoclint
  "docstring-missing-yields", # pydoclint
  "docstring-missing-exception", # pydoclint
  "raise-vanilla-args", # tryceratops
  "non-empty-init-module", # ruff
  "missing-trailing-comma", # conflicts with the formatter
]

[tool.ruff.lint.per-file-ignores]
"src/cuss/_cli.py" = ["print"]
"tests/*" = ["import-private-name", "typing-only-standard-library-import"]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"datetime" = "dt"

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["collections.abc", "types", "typing"]
runtime-evaluated-decorators = ["dataclasses.dataclass"]

[tool.ruff.lint.isort]
combine-as-imports = true
extra-standard-library = ["_typeshed", "typing_extensions"]
known-local-folder = ["cuss"]
